# tasks/main.yml
- name: Create the gvm system group
  group:
    name: "{{ gvm_group }}"
    state: present

- name: Create the gvm system user
  user:
    name: "{{ gvm_user }}"
    group: "{{ gvm_group }}"
    shell: /usr/sbin/nologin
    system: yes
    create_home: no
    groups: sudo
    state: present

- name: Add current user to the gvm group
  user:
    name: "{{ ansible_user }}"
    groups: "{{ gvm_group }}"
    append: yes

- name: Create source, build, and install directories
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - source
    - build
    - install

- name: Créer un fichier d'environnement avec toutes les variables OpenVAS
  copy:
    dest: /etc/profile.d/openvas_env.sh
    content: |
      export INSTALL_PREFIX=/usr/local
      export PATH="$PATH:$INSTALL_PREFIX/sbin"
      export SOURCE_DIR=/opt/source
      export BUILD_DIR=/opt/build
      export INSTALL_DIR=/opt/install
      export GVM_LIBS_VERSION=22.18.0
      export GVMD_VERSION=25.1.1
      export PG_GVM_VERSION=22.6.7
      export GSA_VERSION=24.3.0
      export GSAD_VERSION=24.2.2
      export OPENVAS_SMB_VERSION=22.5.3
      export OPENVAS_SCANNER_VERSION=23.15.3
      export OSPD_OPENVAS_VERSION=22.7.1
      export OPENVAS_DAEMON=23.15.3
    mode: '0644'
  become: yes

- name: Charger les variables d'environnement depuis /etc/profile.d/openvas_env.sh
  shell: |
    bash -c 'source /etc/profile.d/openvas_env.sh' 
  register: env_vars_output
  changed_when: false

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: Install required packages without recommended extras
  apt:
    name:
      - build-essential
      - curl
      - cmake
      - pkg-config
      - python3
      - python3-pip
      - gnupg
    state: present
    install_recommends: no
  become: yes

- name: Download Greenbone signing key
  get_url:
    url: https://www.greenbone.net/GBCommunitySigningKey.asc
    dest: /tmp/GBCommunitySigningKey.asc
    mode: '0644'
  become: yes

- name: Import Greenbone signing key into GPG keyring
  shell: gpg --import /tmp/GBCommunitySigningKey.asc
  args:
    creates: "/root/.gnupg/pubring.kbx"
  become: yes

- name: Set trust level for Greenbone signing key
  shell: echo "8AE4BE429B60A59B311C2E739823FAA60ED1E580:6:" | gpg --import-ownertrust
  become: yes

