---

# roles/ospd-openvas/tasks/main.yml

- name: "[ospd-openvas] Créer le répertoire de téléchargement"
  ansible.builtin.file:
    path: "{{ ospd_openvas_src_dir }}"
    state: directory
    mode: '0755'

- name: "[ospd-openvas] Télécharger les sources"
  ansible.builtin.get_url:
    url: "{{ ospd_openvas_url }}"
    dest: "{{ ospd_openvas_src_dir }}"
    mode: '0644'

- name: "[ospd-openvas] Créer le répertoire d'installation"
  ansible.builtin.file:
    path: "{{ ospd_openvas_install_dir }}"
    state: directory
    mode: '0755'

- name: "[ospd-openvas] Extraire les sources"
  ansible.builtin.unarchive:
    src: "{{ ospd_openvas_src_dir }}/{{ ospd_openvas_tarball  }}"
    dest: "{{ ospd_openvas_install_dir }}"
    remote_src: yes
    extra_opts: [ --strip-components=1 ]

- name: "[ospd-openvas] Installer le paquet Python via pip"
  ansible.builtin.command:
    cmd: python3 -m pip install --root={{ ospd_openvas_install_dir }} --no-warn-script-location .
  args:
    chdir: "{{ ospd_openvas_install_dir }}"
  register: ospd_openvas_pip_install
  changed_when: "'Successfully installed' in ospd_openvas_pip_install.stdout or ospd_openvas_pip_install.rc == 0"
  failed_when: ospd_openvas_pip_install.rc != 0

- name: "[ospd-openvas] Copier les fichiers avec rsync vers /"
  ansible.builtin.command: >
    rsync -a {{ ospd_openvas_install_dir }}/ /
  become: true
