---

- name: "[greenbone-feed-sync] Créer le répertoire d'installation"
  ansible.builtin.file:
    path: "{{ greenbone_feed_sync_install_dir }}"
    state: directory
    mode: '0755'
  tags: 'create-install-dir'

- name: "[greenbone-feed-sync] Installer greenbone-feed-sync for all users"
  ansible.builtin.command:
    cmd: python3 -m pip install --root={{ greenbone_feed_sync_install_dir }} --no-warn-script-location greenbone-feed-sync
  args:
    chdir: "{{ greenbone_feed_sync_install_dir }}"
  register: greenbone_feed_sync_pip_install
  changed_when: "'Successfully installed' in greenbone_feed_sync_pip_install.stdout or greenbone_feed_sync_pip_install.rc == 0"
  failed_when: greenbone_feed_sync_pip_install.rc != 0
  tags: 'install-feed'

- name: "[greenbone-feed-sync] Copier les fichiers avec rsync vers /"
  ansible.builtin.command: >
    rsync -a {{ greenbone_feed_sync_install_dir }}/ /
  become: true
  tags: 'copy'
